sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
before_script: ## 根据你所用的主题和自定义的不同，这里会有所不同
  - npm install -g hexo-cli # 在 CI 环境内安装 Hexo
  - npm install --save hexo-theme-fluid 
branches:
  only:
    - hexo # build hexo branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
  local-dir: public
  target_branch: master
